name: Invictools
version: ${project.version}
main: me.invic.invictools.Invictools
api-version: 1.19
authors: [ Invic ]
description: Gamemodes, Bedwars Bug Fixes, and hosting Utilities for Invic Bedwars
depend: [ BedWars ]
softdepend:
  - PlaceholderAPI
  - WorldEdit
website: solo.to/Invic
commands:
  invictools:
    usage: /invictools help for list of commands
    description: Use '/invictools help' for list of commands
  it:
    usage: /invictools help for list of commands
    description: Use '/invictools help' for list of commands
  lb:
    usage: /lb (bw/bf) (playername)
    description: check leaderboard positions of players
  toggle:
    usage: /toggle (boolean)
    description: toggles plugin features
  teamsize:
    usage: /teamsize (type of change)
    description: swaps map config team sizes
  utility:
    usage: /utility (util)
    description: edits many server options
  queue:
    usage: /queue (bf/bw/selector/join/joinall/spec/host)
    description: handles game queuing
  scen:
    usage: /scen (lucky/etc/list)
    description: handles gamemode queuing. ender list for gamemode list
  invictaview:
    usage: /invictaview
    description: spectates invic if he is not ingame
permissions:
  invictools.*:
    description: Gives access the entire plugin

