name: Invictools
version: ${project.version}
main: me.invic.invictools.Invictools
api-version: 1.19
authors: [ Invic ]
description: Gamemodes, Bedwars Bug Fixes, and hosting Utilities for Invic Bedwars
depend: [ BedWars ]
website: solo.to/Invic
commands:
  invictools:
    usage: /invictools help for list of commands
    description: Use '/invictools help' for list of commands
  it:
    usage: /invictools help for list of commands
    description: Use '/invictools help' for list of commands
  lb:
    usage: /lb (bw/bf) (playername)
    description: check leaderboard positions of players
  toggle:
    usage: /toggle (boolean)
    description: toggles plugin features
permissions:
  invictools.*:
    description: Gives access the entire plugin

